on: [push]
jobs:
  static_analysis:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/idf-cppcheck:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Cppcheck"
        working-directory: ./LaserBlaster
        run: /opt/esp/entrypoint.sh idf.py cppcheck
