on: [push]
jobs:
  static_analysis:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/idf-cppcheck:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Cppcheck
        working-directory: ./LaserBlaster
        run: /opt/esp/entrypoint.sh idf.py cppcheck
      - name: Upload Cppcheck Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-report
          path: LaserBlaster/build/cppcheck_report.xml
  build:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/idf-cppcheck:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Build
        working-directory: ./LaserBlaster
        run: /opt/esp/entrypoint.sh idf.py build
